# local dev: bundle exec jekyll serve

title: "Stock Indicators for Python"
tagline: "Send in historical price quotes and get back desired technical indicators.  Nothing more."

# https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0

# override built-in github url because it does not fetch in build tests
github:
  repository_url: "https://github.com/DaveSkender/Stock.Indicators.Python"
  base_repository_url: "https://github.com/DaveSkender/Stock.Indicators"

sourceurl: "https://github.com/DaveSkender/Stock.Indicators.Python/blob/main/stock_indicators/indicators"
charturl: "https://raw.githubusercontent.com/DaveSkender/Stock.Indicators/main/docs/assets/charts"

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

google_analytics: G-MNKJE3KS9Y

exclude: [
  "*.json",
  "*.lock",
  "*.yml", 
  "*.pptx",
  ".offline",
  "examples/Backtest",
  "examples/ConsoleApp",
  "examples/*.sln",
  "GemFile",
  "node_modules",
  "vendor"
]

include: [
  "contributing.md",
  "guide.md",
  "indicators.html",
  "performance.md",
  "utilities.md"
]

permalink: pretty

# page collections
collections:
  indicators:
    output: true
    permalink: /:path/
    sort_by: "title"