# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Indicators

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: unit tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.12"]
        dotnet-version: ["6.0.x", "8.0.x"]

    env:

      # identifying primary configuration so only one reports coverage
      IS_PRIMARY: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' && matrix.dotnet-version == '8.x' }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          dotnet-quality: "ga"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Test indicators
        id: test-library
        run: |
          pytest -vr A tests pytest-cov --junitxml=pytest.xml

      - name: Post test summary
        uses: MishaKav/pytest-coverage-comment@main
        if: ${{ env.IS_PRIMARY }}
        with:
          pytest-coverage-path: coverage.txt
          junitxml-path: pytest.xml
